application: mapper-perf
module: default
version: mapper
runtime: go
api_version: go1

instance_class: F1
automatic_scaling:
  max_concurrent_requests: 8

handlers:
- url: /.*
  script: _go_app
  login: admin